# Generated by Django 4.1 on 2022-09-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(max_length=100, verbose_name='Маленькое название')),
                ('big_title', models.CharField(max_length=100, verbose_name='Большое название')),
                ('title', models.CharField(max_length=100, verbose_name='Название академии')),
                ('description', models.CharField(max_length=100, verbose_name='Описание академии')),
            ],
        ),
    ]
