# Generated by Django 4.1 on 2022-09-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_homeabout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeabout',
            options={'verbose_name': 'Главная - О нас', 'verbose_name_plural': 'Главная - О нас'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': 'Главная - Статистика', 'verbose_name_plural': 'Главная - Статистика'},
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='description',
            field=models.TextField(verbose_name='Описание академии'),
        ),
    ]
