# Generated by Django 4.1 on 2022-09-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_researchcategory_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='research-images', verbose_name='Банер'),
        ),
        migrations.AddField(
            model_name='research',
            name='image',
            field=models.ImageField(default=1, upload_to='research-images', verbose_name='Изображение на показ'),
            preserve_default=False,
        ),
    ]
