# Generated by Django 4.1 on 2022-09-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_research_banner_research_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='research-banner', verbose_name='Банер'),
        ),
    ]
