# Generated by Django 4.1 on 2022-09-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_alter_research_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('image', models.ImageField(upload_to='research-images', verbose_name='Изображение на показ')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='research-banner', verbose_name='Банер')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': 'Исследования - Иследование', 'verbose_name_plural': 'Исследования - Иследование'},
        ),
    ]
