# Generated by Django 4.1 on 2022-09-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_project_alter_research_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата создания проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='project-banner', verbose_name='Банер'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='project-images', verbose_name='Изображение на показ'),
        ),
    ]
