# Generated by Django 4.1 on 2022-09-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_onlinemagazine'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemagazine',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка кнопки'),
        ),
        migrations.AlterField(
            model_name='onlinemagazine',
            name='button',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название кнопки'),
        ),
    ]
