# Generated by Django 4.1 on 2022-09-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_onlinemagazine_link_alter_onlinemagazine_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='partner-image', verbose_name='Логотип партнера')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на сайт партнера')),
            ],
            options={
                'verbose_name': 'Партнёры',
                'verbose_name_plural': 'Партнёры',
            },
        ),
    ]
