# Generated by Django 4.1 on 2022-09-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_aboutpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='about-image', verbose_name='Банер'),
        ),
    ]
