# Generated by Django 4.1 on 2022-09-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_alter_aboutpage_options_aboutpage_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Банер раздела "О нас"')),
            ],
            options={
                'verbose_name': 'О нас - банер',
                'verbose_name_plural': 'О нас - банер',
            },
        ),
        migrations.CreateModel(
            name='ProjectBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
