# Generated by Django 4.1 on 2022-09-01 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_aboutbanner_projectbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='banner',
        ),
    ]
