# Generated by Django 4.1 on 2022-09-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_remove_aboutpage_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectbanner',
            options={'verbose_name': 'Проекты - банер', 'verbose_name_plural': 'Проекты - банер'},
        ),
        migrations.AddField(
            model_name='projectbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Банер раздела "Проекты"'),
        ),
    ]
