# Generated by Django 4.1 on 2022-09-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_alter_projectbanner_options_projectbanner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название новости')),
                ('date', models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата создания новости')),
                ('tag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег новости')),
                ('image', models.ImageField(upload_to='project-images', verbose_name='Изображение на показ')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='project-banner', verbose_name='Банер')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Банер раздела "Новости"')),
            ],
            options={
                'verbose_name': 'Новости - банер',
                'verbose_name_plural': 'Новости - банер',
            },
        ),
    ]
