# Generated by Django 4.1 on 2022-09-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_news_newsbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Банер раздела "Исследования"')),
            ],
            options={
                'verbose_name': 'Исследования - банер',
                'verbose_name_plural': 'Исследования - банер',
            },
        ),
    ]
