# Generated by Django 4.1 on 2022-09-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0018_researchbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('date', models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата жизни')),
                ('image', models.ImageField(upload_to='gallery-images', verbose_name='Фото автора')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='GalleryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Банер раздела "Галерея"')),
            ],
            options={
                'verbose_name': 'Галерея - банер',
                'verbose_name_plural': 'Галерея - банер',
            },
        ),
    ]
