# Generated by Django 4.1 on 2022-09-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_gallery_gallerybanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Банер раздела "Контакты"')),
            ],
            options={
                'verbose_name': 'Контакты - банер',
                'verbose_name_plural': 'Контакты - банер',
            },
        ),
    ]
