# Generated by Django 4.1 on 2022-09-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0024_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=200, verbose_name='Инстаграм')),
                ('telegram', models.CharField(max_length=200, verbose_name='Телеграм')),
                ('facebook', models.CharField(max_length=200, verbose_name='Фейсбук')),
            ],
            options={
                'verbose_name': 'Соц. сети',
                'verbose_name_plural': 'Соц. сети',
            },
        ),
    ]
