# Generated by Django 4.1 on 2022-09-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0026_siteguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteguide',
            name='link',
            field=models.CharField(default=1, max_length=50, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteguide',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
