# Generated by Django 4.1 on 2022-09-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0028_siteguide_link_oder_alter_siteguide_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManasBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Банер раздела "Манас"')),
            ],
            options={
                'verbose_name': 'Манас - банер',
                'verbose_name_plural': 'Манас - банер',
            },
        ),
    ]
