# Generated by Django 4.1 on 2022-09-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0029_manasbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteguide',
            name='link_oder',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='Ссылка URL'),
        ),
    ]
