# Generated by Django 4.1 on 2022-09-03 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0031_alter_siteguide_link_oder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academy.researchcategory', verbose_name='Категория'),
        ),
    ]
