# Generated by Django 4.1 on 2022-09-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0033_aboutpage_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='text',
            new_name='content',
        ),
    ]
