# Generated by Django 4.1 on 2022-09-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0034_rename_text_aboutpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='department',
            field=models.TextField(blank=True, null=True, verbose_name='Отделы'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание Академии'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission',
            field=models.TextField(blank=True, null=True, verbose_name='Миссия'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Направления'),
        ),
    ]
