# Generated by Django 4.1 on 2022-09-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0035_aboutpage_department_aboutpage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Название Академии'),
        ),
    ]
