# Generated by Django 4.1 on 2022-09-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0036_aboutpage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='mission_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание миссии'),
        ),
    ]
