# Generated by Django 4.1 on 2022-09-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0037_aboutpage_mission_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='content_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание направления'),
        ),
    ]
