# Generated by Django 4.1 on 2022-09-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0038_aboutpage_content_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='tasks',
            field=models.TextField(blank=True, null=True, verbose_name='Название задачи'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='tasks_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Название направления'),
        ),
    ]
