# Generated by Django 4.1 on 2022-09-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0039_aboutpage_tasks_aboutpage_tasks_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
    ]
