# Generated by Django 4.1 on 2022-09-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0041_project_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание новости'),
        ),
    ]
