# Generated by Django 4.1 on 2022-09-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0043_npabanner_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Содержание НПА')),
            ],
            options={
                'verbose_name': 'НПА',
                'verbose_name_plural': 'НПА',
            },
        ),
        migrations.RemoveField(
            model_name='npabanner',
            name='text',
        ),
    ]
