# Generated by Django 4.1 on 2022-09-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0044_npa_remove_npabanner_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
    ]
