# Generated by Django 4.1 on 2022-09-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0046_galleryimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея - Авторы', 'verbose_name_plural': 'Галерея - Авторы'},
        ),
        migrations.AddField(
            model_name='galleryimages',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='gallery-images', verbose_name='Квадратное изображение картины'),
        ),
    ]
