# Generated by Django 4.1 on 2022-09-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0047_alter_gallery_options_galleryimages_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название архива')),
                ('tag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег архива')),
                ('image', models.ImageField(upload_to='project-images', verbose_name='Изображение на показ')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='project-banner', verbose_name='Банер')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Содержание архива')),
            ],
            options={
                'verbose_name': 'Архив',
                'verbose_name_plural': 'Архив',
            },
        ),
        migrations.CreateModel(
            name='ArchiveBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Банер раздела "Архив"')),
            ],
            options={
                'verbose_name': 'Архив - банер',
                'verbose_name_plural': 'Архив - банер',
            },
        ),
    ]
