# Generated by Django 4.1 on 2022-09-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0049_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
    ]
