# Generated by Django 4.1 on 2022-09-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0052_alter_contacts_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Манас содержание')),
            ],
            options={
                'verbose_name': 'Манас',
                'verbose_name_plural': 'Манас',
            },
        ),
    ]
