# Generated by Django 4.1 on 2022-09-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0054_mail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ['-id'], 'verbose_name': 'Письма', 'verbose_name_plural': 'Письма'},
        ),
    ]
