# Generated by Django 4.1 on 2022-09-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0055_alter_mail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manas',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Про Манас'},
        ),
        migrations.AddField(
            model_name='manas',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='project-banner', verbose_name='Банер'),
        ),
        migrations.AddField(
            model_name='manas',
            name='image',
            field=models.ImageField(default=1, upload_to='project-images', verbose_name='Изображение на показ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manas',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег Про Манас'),
        ),
        migrations.AddField(
            model_name='manas',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Название Про Манас'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manas',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание новости'),
        ),
    ]
