# Generated by Django 4.1 on 2022-09-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0056_alter_manas_options_manas_banner_manas_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='tag_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='tag_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название новости'),
        ),
    ]
