# Generated by Django 4.1 on 2022-09-09 07:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0057_news_tag_en_news_tag_ky_news_tag_ru_news_text_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manas',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание новости'),
        ),
    ]
