# Generated by Django 4.1 on 2022-09-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0060_alter_manas_text_alter_manas_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manas',
            name='tag_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег Про Манас'),
        ),
        migrations.AddField(
            model_name='manas',
            name='tag_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег Про Манас'),
        ),
        migrations.AddField(
            model_name='manas',
            name='tag_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег Про Манас'),
        ),
        migrations.AddField(
            model_name='manas',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название Про Манас'),
        ),
        migrations.AddField(
            model_name='manas',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название Про Манас'),
        ),
        migrations.AddField(
            model_name='manas',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название Про Манас'),
        ),
    ]
