# Generated by Django 4.1 on 2022-09-09 08:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0062_aboutpage_content_desc_en_aboutpage_content_desc_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='phone_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Телефон'),
        ),
    ]
