# Generated by Django 4.1 on 2022-09-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0063_contacts_phone_en_contacts_phone_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manas',
            name='test1',
            field=models.CharField(default=1, max_length=200, verbose_name='Кнопка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manas',
            name='test2',
            field=models.ImageField(default=1, upload_to='project-images', verbose_name='Файл прикрепить'),
            preserve_default=False,
        ),
    ]
