# Generated by Django 4.1 on 2022-09-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0064_manas_test1_manas_test2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manas',
            name='test1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Кнопка'),
        ),
        migrations.AlterField(
            model_name='manas',
            name='test2',
            field=models.ImageField(blank=True, null=True, upload_to='project-images', verbose_name='Файл прикрепить'),
        ),
    ]
