# Generated by Django 4.1 on 2022-09-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0065_alter_manas_test1_alter_manas_test2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manas',
            name='test2',
            field=models.FileField(blank=True, null=True, upload_to='project-images', verbose_name='Файл прикрепить'),
        ),
    ]
