# Generated by Django 4.1 on 2022-09-10 13:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0066_alter_manas_test2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manas',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание новости'),
        ),
        migrations.AlterField(
            model_name='manas',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание новости'),
        ),
        migrations.AlterField(
            model_name='manas',
            name='text_ky',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание новости'),
        ),
        migrations.AlterField(
            model_name='manas',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание новости'),
        ),
    ]
