# Generated by Django 4.1 on 2022-09-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0068_remove_manas_text_remove_manas_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManasFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название кнопки')),
                ('file', models.FileField(blank=True, null=True, upload_to='manas-files', verbose_name='Файл прикрепить')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на видео')),
                ('manas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.manas')),
            ],
        ),
    ]
