# Generated by Django 4.1 on 2022-09-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0070_remove_manas_test1_remove_manas_test2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manas',
            options={'verbose_name': 'Про Манас', 'verbose_name_plural': 'Про Манас'},
        ),
        migrations.AlterField(
            model_name='manasfile',
            name='manas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manas_files', to='academy.manas'),
        ),
    ]
