# Generated by Django 4.1 on 2022-09-10 15:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0071_alter_manas_options_alter_manasfile_manas'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='employees',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Телеграм'),
        ),
        migrations.AddField(
            model_name='management',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='management',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='management',
            name='text_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='management',
            name='text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Биография'),
        ),
    ]
