# Generated by Django 4.1 on 2022-09-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0072_employees_instagram_employees_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фейсбук'),
        ),
    ]
