# Generated by Django 4.1 on 2022-09-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0073_employees_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='twitter',
            field=models.CharField(default=1, max_length=200, verbose_name='Твиттер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='vk',
            field=models.CharField(default=1, max_length=200, verbose_name='ВКонтакте'),
            preserve_default=False,
        ),
    ]
